language: c
compiler:
  - gcc
  - clang
env:
  global:
  matrix:
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -qq check
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make test
  - ctest -D Continuous
after_success:
after_failure:
after_script:
