language: c
compiler:
  - gcc
  - clang
env:
  global:
    - CK_VERBOSITY=verbose
  matrix:
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -qq check check-devel
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make check && make test
after_success:
after_failure:
after_script:
