language: c
compiler:
  - gcc
  - clang
env:
  global:
  matrix:
before_install:
  - sudo apt-get update
install:
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make install
  - make test
after_success:
after_failure:
after_script:
